---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    keyvaultName: "multicloud"
    tenantId: "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXXXX"
    cloudName: "AzurePublicCloud"
    objects: |
      array:
        - |
          objectName: multicloud-postgresql-server-password
          objectType: secret

  secretObjects:
    - secretName: db-credentials
      type: Opaque
      data:
        - objectName: multicloud-postgresql-server-password
          key: password
